/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class PermissionSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'roleId', 'updatedAt', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'isBettingEnabled',
    'lastAccessAt',
    'password',
    'status',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBettingEnabled: boolean
  @column.dateTime()
  declare lastAccessAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
