/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'entityId',
    'entityType',
    'id',
    'ipAddress',
    'newValues',
    'oldValues',
    'userAgent',
    'userId',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class PermissionSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'roleId', 'updatedAt', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'isBettingEnabled',
    'lastAccessAt',
    'password',
    'status',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBettingEnabled: boolean
  @column.dateTime()
  declare lastAccessAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}

export class WalletTransactionSchema extends BaseModel {
  static $columns = [
    'amount',
    'balanceAfter',
    'balanceBefore',
    'createdAt',
    'description',
    'id',
    'idempotencyKey',
    'metadata',
    'reference',
    'status',
    'type',
    'userId',
    'walletId',
  ] as const
  $columns = WalletTransactionSchema.$columns
  @column()
  declare amount: string
  @column()
  declare balanceAfter: string
  @column()
  declare balanceBefore: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare metadata: any | null
  @column()
  declare reference: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column()
  declare userId: number
  @column()
  declare walletId: number
}

export class WalletSchema extends BaseModel {
  static $columns = [
    'availableBalance',
    'createdAt',
    'heldBalance',
    'id',
    'updatedAt',
    'userId',
  ] as const
  $columns = WalletSchema.$columns
  @column()
  declare availableBalance: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare heldBalance: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}
