/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'entityId', 'entityType', 'id', 'ipAddress', 'newValues', 'oldValues', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class BetSchema extends BaseModel {
  static $columns = ['amount', 'bettingSideId', 'createdAt', 'eventId', 'id', 'idempotencyKey', 'metadata', 'payoutAmount', 'placedAt', 'reference', 'roundId', 'settledAt', 'status', 'transactionId', 'updatedAt', 'userId'] as const
  $columns = BetSchema.$columns
  @column()
  declare amount: string
  @column()
  declare bettingSideId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare metadata: any | null
  @column()
  declare payoutAmount: string
  @column.dateTime()
  declare placedAt: DateTime
  @column()
  declare reference: string | null
  @column()
  declare roundId: number
  @column.dateTime()
  declare settledAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare transactionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class BettingSideSchema extends BaseModel {
  static $columns = ['code', 'color', 'createdAt', 'eventId', 'id', 'metadata', 'name', 'roundId', 'updatedAt'] as const
  $columns = BettingSideSchema.$columns
  @column()
  declare code: string
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column()
  declare roundId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = ['bettingStatus', 'coverImage', 'createdAt', 'description', 'id', 'isFeatured', 'location', 'name', 'playbackUrl', 'scheduledAt', 'slug', 'status', 'streamStatus', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column()
  declare bettingStatus: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isFeatured: boolean
  @column()
  declare location: string | null
  @column()
  declare name: string
  @column()
  declare playbackUrl: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare streamStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'eventId', 'id', 'messageType', 'moderatedAt', 'moderatedBy', 'status', 'userId'] as const
  $columns = MessageSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare messageType: string
  @column.dateTime()
  declare moderatedAt: DateTime | null
  @column()
  declare moderatedBy: number | null
  @column()
  declare status: string
  @column()
  declare userId: number
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class PermissionSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoundResultSchema extends BaseModel {
  static $columns = ['eventId', 'greenTotal', 'houseCommission', 'id', 'metadata', 'redTotal', 'roundId', 'settledAt', 'totalPayout', 'totalPool', 'totalWinners', 'winningSideId'] as const
  $columns = RoundResultSchema.$columns
  @column()
  declare eventId: number
  @column()
  declare greenTotal: string
  @column()
  declare houseCommission: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare redTotal: string
  @column()
  declare roundId: number
  @column.dateTime()
  declare settledAt: DateTime
  @column()
  declare totalPayout: string
  @column()
  declare totalPool: string
  @column()
  declare totalWinners: number
  @column()
  declare winningSideId: number
}

export class RoundSchema extends BaseModel {
  static $columns = ['bettingClosedAt', 'bettingStatus', 'createdAt', 'eventId', 'finishedAt', 'id', 'openedAt', 'roundNumber', 'startedAt', 'status', 'totalGreen', 'totalPool', 'totalRed', 'updatedAt', 'winningSideId'] as const
  $columns = RoundSchema.$columns
  @column.dateTime()
  declare bettingClosedAt: DateTime | null
  @column()
  declare bettingStatus: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: number
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare openedAt: DateTime | null
  @column()
  declare roundNumber: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalGreen: string
  @column()
  declare totalPool: string
  @column()
  declare totalRed: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winningSideId: number | null
}

export class StreamConfigurationSchema extends BaseModel {
  static $columns = ['createdAt', 'endedAt', 'eventId', 'id', 'ingestUrl', 'metadata', 'playbackUrl', 'provider', 'startedAt', 'status', 'streamKeyEncrypted', 'updatedAt'] as const
  $columns = StreamConfigurationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endedAt: DateTime | null
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ingestUrl: string
  @column()
  declare metadata: any | null
  @column()
  declare playbackUrl: string
  @column()
  declare provider: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare streamKeyEncrypted: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'roleId', 'updatedAt', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isBettingEnabled', 'lastAccessAt', 'password', 'status', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBettingEnabled: boolean
  @column.dateTime()
  declare lastAccessAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}

export class WalletTransactionSchema extends BaseModel {
  static $columns = ['amount', 'balanceAfter', 'balanceBefore', 'createdAt', 'description', 'id', 'idempotencyKey', 'metadata', 'reference', 'status', 'type', 'userId', 'walletId'] as const
  $columns = WalletTransactionSchema.$columns
  @column()
  declare amount: string
  @column()
  declare balanceAfter: string
  @column()
  declare balanceBefore: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare metadata: any | null
  @column()
  declare reference: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column()
  declare userId: number
  @column()
  declare walletId: number
}

export class WalletSchema extends BaseModel {
  static $columns = ['availableBalance', 'createdAt', 'heldBalance', 'id', 'updatedAt', 'userId'] as const
  $columns = WalletSchema.$columns
  @column()
  declare availableBalance: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare heldBalance: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}
